### ISSUE TITLE
'find too many unsuccessfully terminated jobs'

### ISSUE THREAD

**Issue by SimonkingCat** [deepmodeling/dpgen#1043] opened 2022-11-24 04:06 UTC
```find too many unsuccessfully terminated jobs. Too many FP tasks are not converged. Please check your input parameters (e.g.INCAR) or configuration (e.g. POSCAR) in directories 'iter.*.*/02.fp/task.*.*/.' ```

**Comment by HuangJiameng** [comment] 2022-11-25 07:49
detailed description?

**Comment by HuangJiameng** [comment] 2022-12-02 13:50
Hi, have you checked `your input parameters (e.g.INCAR) or configuration (e.g. POSCAR)` to found out  why `Too many FP tasks are not converged`?

**Comment by SimonkingCat** [comment] 2022-12-03 09:30
> Hi, have you checked `your input parameters (e.g.INCAR) or configuration (e.g. POSCAR)` to found out why `Too many FP tasks are not converged`?

Yes, but I cant figure it out. Can I delete these frames to continue the calculation?

**Comment by njzjz** [comment] 2023-10-16 19:04
Duplicate of #399

**Closed by njzjz** 2023-10-16 19:04 UTC
Labels: wontfix
