### ISSUE TITLE
[BUG] skip_relax for DPGEN init (ABACUS) is invalid

### ISSUE THREAD

**Issue by MumuMaster2021** [deepmodeling/dpgen#1450] opened 2024-01-11 08:39 UTC
### Bug summary

I set  the "skip_relax:  true" in param.json, and execute "nohup dpgen init_bulk param.json machine.json 1>log 2>err&" it still will submit the relax job in bohrium and execute stage1 .

### DP-GEN Version

0.12.1

### Platform, Python Version, Remote Platform, etc

bohrium

### Input Files, Running Commands, Error Log, etc.

{
    "init_fp_style": "ABACUS",
    "stages":           [1,2],
    "cell_type":        "fcc",
    "super_cell":       [2, 2, 2],
    "elements":         ["Al", "O"],
    "from_poscar":      true,
    "from_poscar_path": "./strucs/Al-mp-1182868",
    "potcars":          ["./pseudos/Al_ONCV_PBE-1.0.upf", "./pseudos/O_ONCV_PBE-1.0.upf"],
    "orb_files":        ["./pseudos/Al_gga_10au_100Ry_6s6p2d.orb", "./pseudos/O_gga_10au_100Ry_3s3p2d.orb"],
    "skip_relax":       true,
    "relax_incar":      "INPUT",
    "relax_kpt":        "",
    "md_incar" :        "INPUT.md",
    "md_kpt" :          "",
    "scale":            [0.98,0.99,1.00,1.01,1.02],
    "pert_numb":        10,
    "md_nstep" :        10,
    "pert_box":         0.01,
    "pert_atom":        0.01,
    "coll_ndata":       10,
    "_comment":         "that's all"

### Steps to Reproduce

[init-userlszhang.tar.gz](https://github.com/deepmodeling/dpgen/files/13900138/init-userlszhang.tar.gz)

**Comment by MumuMaster2021** [comment] 2024-01-11 08:45
have fixed, the solution is if users want to skip relax, need to execute"nohup dpgen init_bulk param.json 1>log 2>err&" then will skip the stage1.

**Comment by pxlxingliang** [comment] 2024-01-16 03:47
Hi, @njzjz this is not an ABACUS issue. In the flow of init_bulk, key `skip_relax` is only read in stage 2, which is used to control if generate the random structures from the relaxed structure (in stage 1) or not.

**Comment by pxlxingliang** [comment] 2024-01-16 03:51
Hi @MumuMaster2021, if you do not want to execute stage 1, you should remove 1 in the value of `stage`, like "stage": [2],

**Comment by njzjz** [comment] 2024-01-20 22:01
> Hi, @njzjz this is not an ABACUS issue. In the flow of init_bulk, key `skip_relax` is only read in stage 2, which is used to control if generate the random structures from the relaxed structure (in stage 1) or not. 

I see. I'll close this issue since it's not a bug.

**Closed** 2024-01-20 22:01 UTC
Labels: question
