### ISSUE TITLE
offer a KPOINTS option in the param.json

### ISSUE THREAD

**Issue by flamingoXu** [deepmodeling/dpgen#1515] opened 2024-04-11 14:18 UTC
### Summary

Implement an option for specifying custom k-point grids through the param.json in deepmd-kit, addressing the limitations caused by the uniform k-point density across all three dimensions when using KSPACING.

### Detailed Description

2D materials exhibit periodicity solely in-plane, necessitating custom k-point meshes (e.g., Nx x Ny x 1) to accurately compute single-point energies. The current KSPACING parameter uniformly distributes k-points across all three dimensions, which is suboptimal for systems like 2D materials that do not require a dense k-point sampling perpendicular to the plane. Allowing a direct input of the k-point grid as a parameter would provide more precise control over the simulation setup, leading to more accurate results for these types of materials. This enhancement would make deepmd-kit more adaptable for studies involving 2D systems

**Comment by njzjz** [comment] 2024-04-11 21:37
Duplicate of #726.

**Comment by njzjz** [comment] 2024-04-11 21:38
Duplicate of #726

**Closed** 2024-04-14 22:53 UTC
Labels: duplicate, enhancement
