### ISSUE TITLE
[BUG] A seed provided to descriptor

### ISSUE THREAD

**Issue by swome** [deepmodeling/dpgen#458] opened 2021-07-09 02:08 UTC
When generating the input script of deepmd-kit in 00.train, dpgen will append an arguement 'seed' in 'descriptor'. The descriptor type is "hybrid".
While in strict mode of deepmd-kit the arguement 'seed' is not allowed.
And it presents such an error:
"dargs.dargs.ArgumentKeyError: [at location `model/descriptor`] undefined key`seed` is not allowed in strict mode"

**Comment by amcadmus** [comment] 2021-07-09 07:05
The reason of the issue is that the compatibility to deepmd-kit v2.0 does not consider the descriptor type `hybrid`

**Comment by njzjz** [comment] 2021-07-09 07:25
Fixed by #459. Please try to use deepmodeling/dpgen@23e3bd31dd19b3f684fefacfef463ae3ec422491:
```sh
git checkout devel
git pull
pip install .
```

**Closed by njzjz** 2021-07-09 07:25 UTC
Labels: bug
